/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tienda.GeneracionFactura;

import java.awt.Font;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.text.NumberFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tienda.Conexion;

/**
 *
 * @author Juan Miguel
 */
public final class facturacion extends javax.swing.JFrame {

    int fila = -1;
    int subtotal = 0;
    PreparedStatement ps;
    ResultSet rs;
    Connection con = new Conexion().getConnection();
    String[] productos_factura = new String[1];
    JTextArea texto = new JTextArea();
    NumberFormat formatoImporte = NumberFormat.getCurrencyInstance(); //formato pesos

    int cantidad_compra = 0;

    public facturacion() {
        initComponents();
        mostrar();
        this.setLocationRelativeTo(null);
        texto.setEditable(false);
        texto.setFocusable(false);
        texto.setLineWrap(true);
        texto.setFont(new java.awt.Font("Courier New", 0, 10));
        encabezado_factura(texto);
        JScrollPane scroll = new JScrollPane(texto, JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scroll.setBounds(0, 0, JpFactura.getWidth(), JpFactura.getHeight());
        JpFactura.add(scroll);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new rojeru_san.complementos.TableMetro();
        JpFactura = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtTexto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JcSeleccion = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtSubtotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Marca", "Precio venta", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductos.setAltoHead(20);
        tblProductos.setColorBackgoundHead(new java.awt.Color(0, 153, 153));
        tblProductos.setFuenteHead(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);
        if (tblProductos.getColumnModel().getColumnCount() > 0) {
            tblProductos.getColumnModel().getColumn(0).setPreferredWidth(5);
            tblProductos.getColumnModel().getColumn(4).setPreferredWidth(30);
        }

        javax.swing.GroupLayout JpFacturaLayout = new javax.swing.GroupLayout(JpFactura);
        JpFactura.setLayout(JpFacturaLayout);
        JpFacturaLayout.setHorizontalGroup(
            JpFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );
        JpFacturaLayout.setVerticalGroup(
            JpFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        txtTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTextoKeyTyped(evt);
            }
        });

        jLabel2.setText("Buscar: ");

        JcSeleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Marca", "ID" }));

        jButton1.setText("Agregar producto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JcSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(0, 786, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSubtotal)
                    .addComponent(JpFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JcSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JpFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)
                        .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        this.fila = tblProductos.getSelectedRow();

        // TODO add your handling code here:
    }//GEN-LAST:event_tblProductosMouseClicked

    private void txtTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTextoKeyTyped
        busquedaRef(JcSeleccion.getSelectedIndex());
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTextoKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int ind = productos_factura.length;
        if (fila != -1) {
            fijarCantidad fc = new fijarCantidad(this, true);
            fc.setLocationRelativeTo(null);
            fc.setVisible(true);
            cantidad_compra = fc.cantidad;
            if (cantidad_compra != 0) {
                int id = (int) tblProductos.getValueAt(fila, 0);
                int cantidad_factura = cantidad_compra;
                String nombre = (String) tblProductos.getValueAt(fila, 1);

                int espacios = 19 - nombre.length();
                String esp = "";
                for (int i = 1; i <= espacios; i++) {
                    esp += " ";
                };
                try {
                    ps = con.prepareStatement("SELECT * FROM productos WHERE id = ?");
                    ps.setInt(1, (int) tblProductos.getValueAt(fila, 0));
                    rs = ps.executeQuery();
                    rs.next();
                    cantidad_compra = rs.getInt("cantidad") - cantidad_compra;
                    productos_factura[ind - 1] = "UPDATE productos SET cantidad =" + cantidad_compra + " WHERE id =" + (int) tblProductos.getValueAt(fila, 0);
                    ind++;

                    texto.setText(texto.getText() + "\n " + id + "   " + nombre + esp + cantidad_factura + "    ");
                    double precio_producto = rs.getDouble("precio_venta");
                    double precio_total = precio_producto * cantidad_factura;
                    if (cantidad_factura <= 9) {
                        texto.setText(texto.getText() + " " + formatoImporte.format(precio_producto));
                    }
                    if (cantidad_factura >= 10) {
                        texto.setText(texto.getText() + formatoImporte.format(precio_producto));
                    }
                    subtotal += precio_producto;
                    txtSubtotal.setText("SUBTOTAL:           " + formatoImporte.format(subtotal));
                } catch (SQLException ex) {
                    Logger.getLogger(facturacion.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "La cantidad de compra para producto tiene que ser mayor a 0");
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalActionPerformed

    public void mostrar() {
        try {
            DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel();
            ps = con.prepareStatement("SELECT * FROM productos");
            rs = ps.executeQuery();
            int i = 0;

            while (rs.next()) {
                modelo.setNumRows(i + 1);
                modelo.setValueAt(rs.getInt("id"), i, 0);
                modelo.setValueAt(rs.getString("nombre"), i, 1);
                modelo.setValueAt(rs.getString("marca"), i, 2);
                modelo.setValueAt(rs.getDouble("precio_venta"), i, 3);
                modelo.setValueAt(rs.getInt("cantidad"), i, 4);
                i++;
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    public void busquedaRef(int op) {
        try {
            ps = con.prepareStatement("SELECT * FROM productos");
            rs = ps.executeQuery();
            int i = 0;
            if (txtTexto != null) {
                DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel();
                String dato = txtTexto.getText().toLowerCase();
                String palDeter;
                String[] letras = null;
                while (rs.next()) {
                    switch (op) {
                        case 0 ->
                            letras = rs.getString("nombre").toLowerCase().split("");
                        case 1 ->
                            letras = rs.getString("marca").toLowerCase().split("");
                        case 2 ->
                            letras = String.valueOf(rs.getInt("id")).split("");
                    }
                    palDeter = "";
                    if (dato.length() <= letras.length) {
                        for (int j = 0; j < dato.length(); j++) {
                            palDeter += letras[j];
                        }
                        if (dato.equals(palDeter)) {
                            modelo.setNumRows(i + 1);
                            modelo.setValueAt(rs.getInt("id"), i, 0);
                            modelo.setValueAt(rs.getString("nombre"), i, 1);
                            modelo.setValueAt(rs.getString("marca"), i, 2);
                            modelo.setValueAt(rs.getDouble("precio_venta"), i, 3);
                            modelo.setValueAt(rs.getInt("cantidad"), i, 4);
                            i++;
                        }
                    }
                }
            } else {
                mostrar();
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    public void encabezado_factura(JTextArea texto) {
        Date hoy = new Date();
        String enc = """
                     --------------------------------------------
                     Facturacion Supermercado ***
                     Cartagena de indias
                            """ + hoy
                + """
                     
                     --------------------------------------------
                     ID |      NOMBRE      | Qty | P.Unit |   P.Tot
                     """;
        texto.setText(enc);

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new facturacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JcSeleccion;
    private javax.swing.JPanel JpFactura;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.complementos.TableMetro tblProductos;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTexto;
    // End of variables declaration//GEN-END:variables
}
